language: perl
sudo: false
perl:
  - "5.24"
before_install:
  - perlbrew install-cpanm -f
install:
  - (cpanm --installdeps --with-develop -nq .) || cat ~/.cpanm/build.log
script:
  - prove -l
deploy:
  provider: heroku
  api_key:
    secure:$HEROKU_API_KEY
  app: okinawapm-slackbot
