language: perl
sudo: false
perl:
  - "5.24"
before_install:
  - perlbrew install-cpanm -f
install:
  - (cpanm --installdeps --with-develop -nq .) || cat ~/.cpanm/build.log
script:
  - prove -lr xt -j9
