#!perl

use File::Spec;
use Cwd 'getcwd';

BEGIN { unshift @INC, File::Spec->catfile(getcwd, "lib") }
require Okinawa::SlackBot;

Okinawa::SlackBot->new(name => $ENV{BOT_NAME}, token => $ENV{SLACK_TOKEN})->run;